services:
  - docker
install:
  - echo "No hay nada que instalar"
script:
  - docker build -t saludo-samuel .
  - docker tag saludo-samuel aosorio2020/saludo-armando:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push aosorio2020/saludo-armando
